# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Parse Deck
email: parsedeck@datamcfly.com
description: > # this means to ignore newlines until "baseurl:"
  Parse Deck is your parse server hosting platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://parsedeck.com" # the base hostname & protocol for your site
twitter_username: freekrai
github_username:  parsedeck

# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge
paginate: 10

gems:
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem